version: "3.9"

services:

  admin:
    build:
      context: ./admin
    command: /bin/bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001"
    container_name: dj_admin
    ports:
      - "8101:8001"
    environment:
      - DATABASE_URL=postgresql://user:password@db/dron
    depends_on:
      - db

  api_core:
    build:
      context: ./api_core
    container_name: api
    ports:
      - "8100:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/dron
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_dron
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dron
    ports:
      - "6432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
